version: "3.7"
services:
  mailserver:
    image: mailserver
    container_name: mailserver
    hostname: mailserver
    privileged: true
    command: /sbin/init
    expose:
      - "25"
    ports:
      - 993:993
    restart: always
