version: "3.7"
services:
  postfix:
    image: postfix
    container_name: postfix
    hostname: postfix
    privileged: true
    command: /sbin/init
#    volumes:
#      - ./volumes/mongodb/root:/root:ro # Initialize script
#      - ./volumes/mongodb/etc/mongod-keyfile:/etc/mongod-keyfile:ro # Permission: 600
    ports:
      - 993:993
      - 995:995
      - 587:587
      - 9205:9205
      - 10025:10025
    restart: always

  postfix-client:
    image: postfix-client
    container_name: postfix-client
    hostname: postfix-client
    privileged: true
    volumes:
      - ./Dockerfiles/sendmail.py /usr/share/sendmail.py
    restart: always

  relay-server:
    image: mailhog/mailhog
    container_name: relay
    hostname: relay
    ports:
      - 1025:1025
      - 8025:8025
    restart: always

