version: "3.7"
services:
  mailserver:
    image: mailserver
    container_name: mailserver
    hostname: mailserver
    privileged: true
    command: /sbin/init
    # expose:
    #  - "25"
    ports:
      - 993:993
      - 995:995
      - 110:110
      - 143:143
    restart: always
