# For development by VSCode

# Base image is debian
FROM python:3.7
LABEL Name=kk Version=0.0.1

# Localize
RUN apt-get update
RUN apt-get -y install locales && \
    localedef -f UTF-8 -i ja_JP ja_JP.UTF-8
ENV LANG ja_JP.UTF-8
ENV LANGUAGE ja_JP:ja
ENV LC_ALL ja_JP.UTF-8
ENV TZ JST-9

# update pip to latest
RUN pip install --upgrade pip && \
    pip install requests

COPY ./Dockerfiles/sendmail.py /usr/local/.

EXPOSE 80

COPY ./Dockerfiles/start.sh /usr/local/etc/start.sh
RUN chmod +x /usr/local/etc/start.sh
ENTRYPOINT [ "sh", "/usr/local/etc/start.sh" ]